global:
  K_si:
    initial_value: 20
    constant: false
    upper: 1000
    lower: 0.01
  K_n:
    initial_value: 300
    constant: false
    upper: 10000
    lower: 0.01
  v_r:
    initial_value: 1e9
    constant: true
    upper: null
    lower: null
r1:
  K_s:
    initial_value: 15.0
    constant: false
    upper: 1000
    lower: 0.01
r2:
  k_2:
    initial_value: 26000.0
    constant: false
    upper: 1e6
    lower: 1.0
r5:
  k_6:
    initial_value: 1e5
    constant: false
    upper: 1e7
    lower: 1.0
r6:
  k_3:
    initial_value: 25000
    constant: false
    upper: 1e6
    lower: 1.0
r7:
  K_pg:
    initial_value: 12
    constant: false
    upper: 1000
    lower: 0.01
r9:
  k_5:
    initial_value: 30000
    constant: false
    upper: 1e6
    lower: 1.0
r10:
  k_4:
    initial_value: 4.4e6
    constant: false
    upper: 1e8
    lower: 1.0
  k_4b:
    initial_value: 5.5e5
    constant: false
    upper: 1e8
    lower: 1.0
r11:
  K_p:
    initial_value: 40
    constant: false
    upper: 1000
    lower: 0.01
r12:
  k_d:
    initial_value: 0.04
    constant: false
    upper: 1.0
    lower: 0.001

